// Auto-generated question bank from freundeskreis_350_echte_freitextfragen.json
// Deduplicated freitext questions grouped by category.

import type { MockQuestion } from "./mock-data";

export const QUESTION_BANK: Record<string, string[]> = {
  personality: ["Welche Eigenschaft macht diese Person unverwechselbar?","Was würden Fremde nach fünf Minuten über sie sagen?","Welche Stärke zeigt sie im Alltag?","Welche Seite von ihr kennen zu wenige Menschen?","Wann wirkt sie am authentischsten?","Was macht sie interessant?","Welche Eigenschaft fällt sofort auf?","Welche Eigenschaft entdeckt man erst später?","Was macht sie sympathisch?","Wofür steht diese Person?","Welche Werte verkörpert sie?","Was macht sie mutig?","Was macht sie besonders menschlich?","Welche Eigenschaft bewunderst du?","Was macht sie einzigartig?","Welche Stärke unterschätzt sie?","Was macht sie glaubwürdig?","Welche Eigenschaft würden andere vermissen?","Was zeichnet ihren Charakter aus?","Wann zeigt sie Größe?","Was macht sie inspirierend?","Welche Eigenschaft macht sie liebenswert?","Wie wirkt sie auf neue Menschen?","Was macht sie stark?","Welche Eigenschaft passt perfekt zu ihr?","Was macht sie besonders angenehm?","Wie beschreibt ihr Lachen sie?","Was verrät viel über ihren Charakter?","Welche Eigenschaft überrascht bei ihr?","Was macht sie unverkennbar?","Welche Rolle übernimmt sie oft?","Was macht sie wertvoll für andere?","Welche Qualität schätzt du besonders?","Was macht sie reflektiert?","Wie geht sie mit Fehlern um?","Was macht sie ehrlich?","Wann zeigt sie Haltung?","Was macht sie bodenständig?","Welche Eigenschaft wird unterschätzt?","Was macht sie selbstbewusst?","Welche Eigenschaft sollte sie öfter zeigen?","Was macht sie ausdrucksstark?","Was macht sie angenehm im Umgang?","Welche Eigenschaft macht sie stark in Krisen?","Was macht sie optimistisch?","Was macht sie offen für Neues?","Welche Eigenschaft sollte jeder kennen?","Was macht sie bemerkenswert?","Was macht sie charakterstark?","Was sollte sie über sich selbst wissen?"],
  friendship: ["Warum bist du froh, dass du diese Person kennst?","Wann war sie für dich da?","Was macht sie zu einer guten Freundin oder einem guten Freund?","Welche Erinnerung verbindest du mit ihr?","Wann hat sie dich unterstützt?","Was macht sie loyal?","Wie zeigt sie Freundschaft?","Was macht sie zu einem sicheren Hafen?","Wann hat sie dich positiv überrascht?","Was macht eure Freundschaft besonders?","Warum bist du froh, dass du diese Person kennst – und warum?","Wann war sie für dich da – und warum?","Was macht sie zu einer guten Freundin oder einem guten Freund – und warum?","Welche Erinnerung verbindest du mit ihr – und warum?","Wann hat sie dich unterstützt – und warum?","Was macht sie loyal – und warum?","Wie zeigt sie Freundschaft – und warum?","Was macht sie zu einem sicheren Hafen – und warum?","Wann hat sie dich positiv überrascht – und warum?","Was macht eure Freundschaft besonders – und warum?"],
  humor: ["Was ist das Lustigste an dieser Person?","Welcher Insider gehört zu ihr?","Welches Meme beschreibt sie?","Welche Geschichte bringt dich wegen ihr zum Lachen?","Welcher Running Gag passt zu ihr?","Welcher Emoji ist sie?","Welche Sitcom-Figur erinnert an sie?","Was war ihr lustigster Moment?","Welchen absurden Titel würde ihre Biografie tragen?","Womit bringt sie Menschen zum Lachen?","Was ist das Lustigste an dieser Person – und warum?","Welcher Insider gehört zu ihr – und warum?","Welches Meme beschreibt sie – und warum?","Welche Geschichte bringt dich wegen ihr zum Lachen – und warum?","Welcher Running Gag passt zu ihr – und warum?","Welcher Emoji ist sie – und warum?","Welche Sitcom-Figur erinnert an sie – und warum?","Was war ihr lustigster Moment – und warum?","Welchen absurden Titel würde ihre Biografie tragen – und warum?","Womit bringt sie Menschen zum Lachen – und warum?"],
  strengths: ["Was kann diese Person besonders gut?","Welche Stärke sieht sie selbst nicht?","Worin würdest du sie um Rat fragen?","Was macht sie kompetent?","Welche Herausforderung hat sie gut gemeistert?","Worin ist sie Vorbild?","Was kann sie besser als die meisten Menschen?","Welche Fähigkeit beeindruckt dich?","Wo hat sie großes Potenzial?","Welche Stärke wird oft übersehen?","Was kann diese Person besonders gut – und warum?","Welche Stärke sieht sie selbst nicht – und warum?","Worin würdest du sie um Rat fragen – und warum?","Was macht sie kompetent – und warum?","Welche Herausforderung hat sie gut gemeistert – und warum?","Worin ist sie Vorbild – und warum?","Was kann sie besser als die meisten Menschen – und warum?","Welche Fähigkeit beeindruckt dich – und warum?","Wo hat sie großes Potenzial – und warum?","Welche Stärke wird oft übersehen – und warum?"],
  vibes: ["Welcher Song beschreibt sie?","Welche Farbe hat ihre Energie?","Welches Tier passt zu ihr?","Welche Jahreszeit wäre sie?","Welcher Ort erinnert an sie?","Welcher Filmcharakter hat ihren Vibe?","Welche Playlist wäre sie?","Welches Getränk wäre sie?","Welche Ästhetik passt zu ihr?","Welche Stadt wäre sie?","Welcher Song beschreibt sie – und warum?","Welche Farbe hat ihre Energie – und warum?","Welches Tier passt zu ihr – und warum?","Welche Jahreszeit wäre sie – und warum?","Welcher Ort erinnert an sie – und warum?","Welcher Filmcharakter hat ihren Vibe – und warum?","Welche Playlist wäre sie – und warum?","Welches Getränk wäre sie – und warum?","Welche Ästhetik passt zu ihr – und warum?","Welche Stadt wäre sie – und warum?"],
  dating: ["Welche Green Flag beschreibt sie?","Warum wäre sie ein guter Partner?","Wie zeigt sie Zuneigung?","Was macht sie attraktiv?","Was macht Zeit mit ihr angenehm?","Welche Eigenschaft schätzt man in einer Beziehung?","Was macht sie charmant?","Wie sorgt sie für Vertrauen?","Warum fühlt man sich bei ihr wohl?","Was macht sie zu einem Fang?","Welche Green Flag beschreibt sie – und warum?","Warum wäre sie ein guter Partner – und warum?","Wie zeigt sie Zuneigung – und warum?","Was macht sie attraktiv – und warum?","Was macht Zeit mit ihr angenehm – und warum?","Welche Eigenschaft schätzt man in einer Beziehung – und warum?","Was macht sie charmant – und warum?","Wie sorgt sie für Vertrauen – und warum?","Warum fühlt man sich bei ihr wohl – und warum?","Was macht sie zu einem Fang – und warum?"],
  memories: ["Welche Erinnerung beschreibt sie perfekt?","Welches Abenteuer verbindest du mit ihr?","Wann hat sie alle überrascht?","Welche Geschichte erzählst du gerne über sie?","Welcher gemeinsame Moment bleibt unvergessen?","Wann war sie besonders mutig?","Welche Erinnerung bringt dich zum Schmunzeln?","Wann war sie Hauptcharakter der Geschichte?","Welcher Zufall erinnert dich an sie?","Welche Erinnerung zeigt ihren Charakter?","Welche Erinnerung beschreibt sie perfekt – und warum?","Welches Abenteuer verbindest du mit ihr – und warum?","Wann hat sie alle überrascht – und warum?","Welche Geschichte erzählst du gerne über sie – und warum?","Welcher gemeinsame Moment bleibt unvergessen – und warum?","Wann war sie besonders mutig – und warum?","Welche Erinnerung bringt dich zum Schmunzeln – und warum?","Wann war sie Hauptcharakter der Geschichte – und warum?","Welcher Zufall erinnert dich an sie – und warum?","Welche Erinnerung zeigt ihren Charakter – und warum?"],
  future: ["Wo siehst du diese Person in zehn Jahren?","Welche Fähigkeit wird ihr noch helfen?","Worin sollte sie mehr Vertrauen haben?","Welchen Traum sollte sie verfolgen?","Was würdest du ihr für die Zukunft wünschen?","Worauf wird sie später stolz sein?","Welche Chance sollte sie nutzen?","Welches Potenzial hat sie?","Was wird sie erreichen?","Was sollte sie unbedingt ausprobieren?","Wo siehst du diese Person in zehn Jahren – und warum?","Welche Fähigkeit wird ihr noch helfen – und warum?","Worin sollte sie mehr Vertrauen haben – und warum?","Welchen Traum sollte sie verfolgen – und warum?","Was würdest du ihr für die Zukunft wünschen – und warum?","Worauf wird sie später stolz sein – und warum?","Welche Chance sollte sie nutzen – und warum?","Welches Potenzial hat sie – und warum?","Was wird sie erreichen – und warum?","Was sollte sie unbedingt ausprobieren – und warum?"],
  deep_talk: ["Was sollte diese Person öfter über sich selbst glauben?","Welche Wahrheit sollte sie hören?","Was macht sie wirklich glücklich?","Welche Stärke trägt sie durch schwere Zeiten?","Was macht ihr Leben wertvoll?","Welche Eigenschaft macht die Welt besser?","Was lernt man von ihr?","Was macht sie innerlich stark?","Was gibt sie anderen mit?","Was macht sie bedeutend?","Was sollte diese Person öfter über sich selbst glauben – und warum?","Welche Wahrheit sollte sie hören – und warum?","Was macht sie wirklich glücklich – und warum?","Welche Stärke trägt sie durch schwere Zeiten – und warum?","Was macht ihr Leben wertvoll – und warum?","Welche Eigenschaft macht die Welt besser – und warum?","Was lernt man von ihr – und warum?","Was macht sie innerlich stark – und warum?","Was gibt sie anderen mit – und warum?","Was macht sie bedeutend – und warum?"],
  creative: ["Welche Superkraft hätte sie?","Welches Pokémon wäre sie?","Welche Fantasyklasse wäre sie?","Welches Buchgenre beschreibt sie?","Welches Videospiel wäre sie?","Welches magische Artefakt wäre sie?","Welcher Planet passt zu ihr?","Welche erfundene Auszeichnung würde sie gewinnen?","Welcher Schatz wäre nach ihr benannt?","Welche Legende würde über sie erzählt werden?","Welche Superkraft hätte sie – und warum?","Welches Pokémon wäre sie – und warum?","Welche Fantasyklasse wäre sie – und warum?","Welches Buchgenre beschreibt sie – und warum?","Welches Videospiel wäre sie – und warum?","Welches magische Artefakt wäre sie – und warum?","Welcher Planet passt zu ihr – und warum?","Welche erfundene Auszeichnung würde sie gewinnen – und warum?","Welcher Schatz wäre nach ihr benannt – und warum?","Welche Legende würde über sie erzählt werden – und warum?"],
};

export const ALL_QUESTIONS: MockQuestion[] = [
  { id: "q-personality-0", text: "Welche Eigenschaft macht diese Person unverwechselbar?" },
  { id: "q-personality-1", text: "Was würden Fremde nach fünf Minuten über sie sagen?" },
  { id: "q-personality-2", text: "Welche Stärke zeigt sie im Alltag?" },
  { id: "q-personality-3", text: "Welche Seite von ihr kennen zu wenige Menschen?" },
  { id: "q-personality-4", text: "Wann wirkt sie am authentischsten?" },
  { id: "q-personality-5", text: "Was macht sie interessant?" },
  { id: "q-personality-6", text: "Welche Eigenschaft fällt sofort auf?" },
  { id: "q-personality-7", text: "Welche Eigenschaft entdeckt man erst später?" },
  { id: "q-personality-8", text: "Was macht sie sympathisch?" },
  { id: "q-personality-9", text: "Wofür steht diese Person?" },
  { id: "q-personality-10", text: "Welche Werte verkörpert sie?" },
  { id: "q-personality-11", text: "Was macht sie mutig?" },
  { id: "q-personality-12", text: "Was macht sie besonders menschlich?" },
  { id: "q-personality-13", text: "Welche Eigenschaft bewunderst du?" },
  { id: "q-personality-14", text: "Was macht sie einzigartig?" },
  { id: "q-personality-15", text: "Welche Stärke unterschätzt sie?" },
  { id: "q-personality-16", text: "Was macht sie glaubwürdig?" },
  { id: "q-personality-17", text: "Welche Eigenschaft würden andere vermissen?" },
  { id: "q-personality-18", text: "Was zeichnet ihren Charakter aus?" },
  { id: "q-personality-19", text: "Wann zeigt sie Größe?" },
  { id: "q-personality-20", text: "Was macht sie inspirierend?" },
  { id: "q-personality-21", text: "Welche Eigenschaft macht sie liebenswert?" },
  { id: "q-personality-22", text: "Wie wirkt sie auf neue Menschen?" },
  { id: "q-personality-23", text: "Was macht sie stark?" },
  { id: "q-personality-24", text: "Welche Eigenschaft passt perfekt zu ihr?" },
  { id: "q-personality-25", text: "Was macht sie besonders angenehm?" },
  { id: "q-personality-26", text: "Wie beschreibt ihr Lachen sie?" },
  { id: "q-personality-27", text: "Was verrät viel über ihren Charakter?" },
  { id: "q-personality-28", text: "Welche Eigenschaft überrascht bei ihr?" },
  { id: "q-personality-29", text: "Was macht sie unverkennbar?" },
  { id: "q-personality-30", text: "Welche Rolle übernimmt sie oft?" },
  { id: "q-personality-31", text: "Was macht sie wertvoll für andere?" },
  { id: "q-personality-32", text: "Welche Qualität schätzt du besonders?" },
  { id: "q-personality-33", text: "Was macht sie reflektiert?" },
  { id: "q-personality-34", text: "Wie geht sie mit Fehlern um?" },
  { id: "q-personality-35", text: "Was macht sie ehrlich?" },
  { id: "q-personality-36", text: "Wann zeigt sie Haltung?" },
  { id: "q-personality-37", text: "Was macht sie bodenständig?" },
  { id: "q-personality-38", text: "Welche Eigenschaft wird unterschätzt?" },
  { id: "q-personality-39", text: "Was macht sie selbstbewusst?" },
  { id: "q-personality-40", text: "Welche Eigenschaft sollte sie öfter zeigen?" },
  { id: "q-personality-41", text: "Was macht sie ausdrucksstark?" },
  { id: "q-personality-42", text: "Was macht sie angenehm im Umgang?" },
  { id: "q-personality-43", text: "Welche Eigenschaft macht sie stark in Krisen?" },
  { id: "q-personality-44", text: "Was macht sie optimistisch?" },
  { id: "q-personality-45", text: "Was macht sie offen für Neues?" },
  { id: "q-personality-46", text: "Welche Eigenschaft sollte jeder kennen?" },
  { id: "q-personality-47", text: "Was macht sie bemerkenswert?" },
  { id: "q-personality-48", text: "Was macht sie charakterstark?" },
  { id: "q-personality-49", text: "Was sollte sie über sich selbst wissen?" },
  { id: "q-friendship-50", text: "Warum bist du froh, dass du diese Person kennst?" },
  { id: "q-friendship-51", text: "Wann war sie für dich da?" },
  { id: "q-friendship-52", text: "Was macht sie zu einer guten Freundin oder einem guten Freund?" },
  { id: "q-friendship-53", text: "Welche Erinnerung verbindest du mit ihr?" },
  { id: "q-friendship-54", text: "Wann hat sie dich unterstützt?" },
  { id: "q-friendship-55", text: "Was macht sie loyal?" },
  { id: "q-friendship-56", text: "Wie zeigt sie Freundschaft?" },
  { id: "q-friendship-57", text: "Was macht sie zu einem sicheren Hafen?" },
  { id: "q-friendship-58", text: "Wann hat sie dich positiv überrascht?" },
  { id: "q-friendship-59", text: "Was macht eure Freundschaft besonders?" },
  { id: "q-friendship-60", text: "Warum bist du froh, dass du diese Person kennst – und warum?" },
  { id: "q-friendship-61", text: "Wann war sie für dich da – und warum?" },
  { id: "q-friendship-62", text: "Was macht sie zu einer guten Freundin oder einem guten Freund – und warum?" },
  { id: "q-friendship-63", text: "Welche Erinnerung verbindest du mit ihr – und warum?" },
  { id: "q-friendship-64", text: "Wann hat sie dich unterstützt – und warum?" },
  { id: "q-friendship-65", text: "Was macht sie loyal – und warum?" },
  { id: "q-friendship-66", text: "Wie zeigt sie Freundschaft – und warum?" },
  { id: "q-friendship-67", text: "Was macht sie zu einem sicheren Hafen – und warum?" },
  { id: "q-friendship-68", text: "Wann hat sie dich positiv überrascht – und warum?" },
  { id: "q-friendship-69", text: "Was macht eure Freundschaft besonders – und warum?" },
  { id: "q-humor-70", text: "Was ist das Lustigste an dieser Person?" },
  { id: "q-humor-71", text: "Welcher Insider gehört zu ihr?" },
  { id: "q-humor-72", text: "Welches Meme beschreibt sie?" },
  { id: "q-humor-73", text: "Welche Geschichte bringt dich wegen ihr zum Lachen?" },
  { id: "q-humor-74", text: "Welcher Running Gag passt zu ihr?" },
  { id: "q-humor-75", text: "Welcher Emoji ist sie?" },
  { id: "q-humor-76", text: "Welche Sitcom-Figur erinnert an sie?" },
  { id: "q-humor-77", text: "Was war ihr lustigster Moment?" },
  { id: "q-humor-78", text: "Welchen absurden Titel würde ihre Biografie tragen?" },
  { id: "q-humor-79", text: "Womit bringt sie Menschen zum Lachen?" },
  { id: "q-humor-80", text: "Was ist das Lustigste an dieser Person – und warum?" },
  { id: "q-humor-81", text: "Welcher Insider gehört zu ihr – und warum?" },
  { id: "q-humor-82", text: "Welches Meme beschreibt sie – und warum?" },
  { id: "q-humor-83", text: "Welche Geschichte bringt dich wegen ihr zum Lachen – und warum?" },
  { id: "q-humor-84", text: "Welcher Running Gag passt zu ihr – und warum?" },
  { id: "q-humor-85", text: "Welcher Emoji ist sie – und warum?" },
  { id: "q-humor-86", text: "Welche Sitcom-Figur erinnert an sie – und warum?" },
  { id: "q-humor-87", text: "Was war ihr lustigster Moment – und warum?" },
  { id: "q-humor-88", text: "Welchen absurden Titel würde ihre Biografie tragen – und warum?" },
  { id: "q-humor-89", text: "Womit bringt sie Menschen zum Lachen – und warum?" },
  { id: "q-strengths-90", text: "Was kann diese Person besonders gut?" },
  { id: "q-strengths-91", text: "Welche Stärke sieht sie selbst nicht?" },
  { id: "q-strengths-92", text: "Worin würdest du sie um Rat fragen?" },
  { id: "q-strengths-93", text: "Was macht sie kompetent?" },
  { id: "q-strengths-94", text: "Welche Herausforderung hat sie gut gemeistert?" },
  { id: "q-strengths-95", text: "Worin ist sie Vorbild?" },
  { id: "q-strengths-96", text: "Was kann sie besser als die meisten Menschen?" },
  { id: "q-strengths-97", text: "Welche Fähigkeit beeindruckt dich?" },
  { id: "q-strengths-98", text: "Wo hat sie großes Potenzial?" },
  { id: "q-strengths-99", text: "Welche Stärke wird oft übersehen?" },
  { id: "q-strengths-100", text: "Was kann diese Person besonders gut – und warum?" },
  { id: "q-strengths-101", text: "Welche Stärke sieht sie selbst nicht – und warum?" },
  { id: "q-strengths-102", text: "Worin würdest du sie um Rat fragen – und warum?" },
  { id: "q-strengths-103", text: "Was macht sie kompetent – und warum?" },
  { id: "q-strengths-104", text: "Welche Herausforderung hat sie gut gemeistert – und warum?" },
  { id: "q-strengths-105", text: "Worin ist sie Vorbild – und warum?" },
  { id: "q-strengths-106", text: "Was kann sie besser als die meisten Menschen – und warum?" },
  { id: "q-strengths-107", text: "Welche Fähigkeit beeindruckt dich – und warum?" },
  { id: "q-strengths-108", text: "Wo hat sie großes Potenzial – und warum?" },
  { id: "q-strengths-109", text: "Welche Stärke wird oft übersehen – und warum?" },
  { id: "q-vibes-110", text: "Welcher Song beschreibt sie?" },
  { id: "q-vibes-111", text: "Welche Farbe hat ihre Energie?" },
  { id: "q-vibes-112", text: "Welches Tier passt zu ihr?" },
  { id: "q-vibes-113", text: "Welche Jahreszeit wäre sie?" },
  { id: "q-vibes-114", text: "Welcher Ort erinnert an sie?" },
  { id: "q-vibes-115", text: "Welcher Filmcharakter hat ihren Vibe?" },
  { id: "q-vibes-116", text: "Welche Playlist wäre sie?" },
  { id: "q-vibes-117", text: "Welches Getränk wäre sie?" },
  { id: "q-vibes-118", text: "Welche Ästhetik passt zu ihr?" },
  { id: "q-vibes-119", text: "Welche Stadt wäre sie?" },
  { id: "q-vibes-120", text: "Welcher Song beschreibt sie – und warum?" },
  { id: "q-vibes-121", text: "Welche Farbe hat ihre Energie – und warum?" },
  { id: "q-vibes-122", text: "Welches Tier passt zu ihr – und warum?" },
  { id: "q-vibes-123", text: "Welche Jahreszeit wäre sie – und warum?" },
  { id: "q-vibes-124", text: "Welcher Ort erinnert an sie – und warum?" },
  { id: "q-vibes-125", text: "Welcher Filmcharakter hat ihren Vibe – und warum?" },
  { id: "q-vibes-126", text: "Welche Playlist wäre sie – und warum?" },
  { id: "q-vibes-127", text: "Welches Getränk wäre sie – und warum?" },
  { id: "q-vibes-128", text: "Welche Ästhetik passt zu ihr – und warum?" },
  { id: "q-vibes-129", text: "Welche Stadt wäre sie – und warum?" },
  { id: "q-dating-130", text: "Welche Green Flag beschreibt sie?" },
  { id: "q-dating-131", text: "Warum wäre sie ein guter Partner?" },
  { id: "q-dating-132", text: "Wie zeigt sie Zuneigung?" },
  { id: "q-dating-133", text: "Was macht sie attraktiv?" },
  { id: "q-dating-134", text: "Was macht Zeit mit ihr angenehm?" },
  { id: "q-dating-135", text: "Welche Eigenschaft schätzt man in einer Beziehung?" },
  { id: "q-dating-136", text: "Was macht sie charmant?" },
  { id: "q-dating-137", text: "Wie sorgt sie für Vertrauen?" },
  { id: "q-dating-138", text: "Warum fühlt man sich bei ihr wohl?" },
  { id: "q-dating-139", text: "Was macht sie zu einem Fang?" },
  { id: "q-dating-140", text: "Welche Green Flag beschreibt sie – und warum?" },
  { id: "q-dating-141", text: "Warum wäre sie ein guter Partner – und warum?" },
  { id: "q-dating-142", text: "Wie zeigt sie Zuneigung – und warum?" },
  { id: "q-dating-143", text: "Was macht sie attraktiv – und warum?" },
  { id: "q-dating-144", text: "Was macht Zeit mit ihr angenehm – und warum?" },
  { id: "q-dating-145", text: "Welche Eigenschaft schätzt man in einer Beziehung – und warum?" },
  { id: "q-dating-146", text: "Was macht sie charmant – und warum?" },
  { id: "q-dating-147", text: "Wie sorgt sie für Vertrauen – und warum?" },
  { id: "q-dating-148", text: "Warum fühlt man sich bei ihr wohl – und warum?" },
  { id: "q-dating-149", text: "Was macht sie zu einem Fang – und warum?" },
  { id: "q-memories-150", text: "Welche Erinnerung beschreibt sie perfekt?" },
  { id: "q-memories-151", text: "Welches Abenteuer verbindest du mit ihr?" },
  { id: "q-memories-152", text: "Wann hat sie alle überrascht?" },
  { id: "q-memories-153", text: "Welche Geschichte erzählst du gerne über sie?" },
  { id: "q-memories-154", text: "Welcher gemeinsame Moment bleibt unvergessen?" },
  { id: "q-memories-155", text: "Wann war sie besonders mutig?" },
  { id: "q-memories-156", text: "Welche Erinnerung bringt dich zum Schmunzeln?" },
  { id: "q-memories-157", text: "Wann war sie Hauptcharakter der Geschichte?" },
  { id: "q-memories-158", text: "Welcher Zufall erinnert dich an sie?" },
  { id: "q-memories-159", text: "Welche Erinnerung zeigt ihren Charakter?" },
  { id: "q-memories-160", text: "Welche Erinnerung beschreibt sie perfekt – und warum?" },
  { id: "q-memories-161", text: "Welches Abenteuer verbindest du mit ihr – und warum?" },
  { id: "q-memories-162", text: "Wann hat sie alle überrascht – und warum?" },
  { id: "q-memories-163", text: "Welche Geschichte erzählst du gerne über sie – und warum?" },
  { id: "q-memories-164", text: "Welcher gemeinsame Moment bleibt unvergessen – und warum?" },
  { id: "q-memories-165", text: "Wann war sie besonders mutig – und warum?" },
  { id: "q-memories-166", text: "Welche Erinnerung bringt dich zum Schmunzeln – und warum?" },
  { id: "q-memories-167", text: "Wann war sie Hauptcharakter der Geschichte – und warum?" },
  { id: "q-memories-168", text: "Welcher Zufall erinnert dich an sie – und warum?" },
  { id: "q-memories-169", text: "Welche Erinnerung zeigt ihren Charakter – und warum?" },
  { id: "q-future-170", text: "Wo siehst du diese Person in zehn Jahren?" },
  { id: "q-future-171", text: "Welche Fähigkeit wird ihr noch helfen?" },
  { id: "q-future-172", text: "Worin sollte sie mehr Vertrauen haben?" },
  { id: "q-future-173", text: "Welchen Traum sollte sie verfolgen?" },
  { id: "q-future-174", text: "Was würdest du ihr für die Zukunft wünschen?" },
  { id: "q-future-175", text: "Worauf wird sie später stolz sein?" },
  { id: "q-future-176", text: "Welche Chance sollte sie nutzen?" },
  { id: "q-future-177", text: "Welches Potenzial hat sie?" },
  { id: "q-future-178", text: "Was wird sie erreichen?" },
  { id: "q-future-179", text: "Was sollte sie unbedingt ausprobieren?" },
  { id: "q-future-180", text: "Wo siehst du diese Person in zehn Jahren – und warum?" },
  { id: "q-future-181", text: "Welche Fähigkeit wird ihr noch helfen – und warum?" },
  { id: "q-future-182", text: "Worin sollte sie mehr Vertrauen haben – und warum?" },
  { id: "q-future-183", text: "Welchen Traum sollte sie verfolgen – und warum?" },
  { id: "q-future-184", text: "Was würdest du ihr für die Zukunft wünschen – und warum?" },
  { id: "q-future-185", text: "Worauf wird sie später stolz sein – und warum?" },
  { id: "q-future-186", text: "Welche Chance sollte sie nutzen – und warum?" },
  { id: "q-future-187", text: "Welches Potenzial hat sie – und warum?" },
  { id: "q-future-188", text: "Was wird sie erreichen – und warum?" },
  { id: "q-future-189", text: "Was sollte sie unbedingt ausprobieren – und warum?" },
  { id: "q-deep_talk-190", text: "Was sollte diese Person öfter über sich selbst glauben?" },
  { id: "q-deep_talk-191", text: "Welche Wahrheit sollte sie hören?" },
  { id: "q-deep_talk-192", text: "Was macht sie wirklich glücklich?" },
  { id: "q-deep_talk-193", text: "Welche Stärke trägt sie durch schwere Zeiten?" },
  { id: "q-deep_talk-194", text: "Was macht ihr Leben wertvoll?" },
  { id: "q-deep_talk-195", text: "Welche Eigenschaft macht die Welt besser?" },
  { id: "q-deep_talk-196", text: "Was lernt man von ihr?" },
  { id: "q-deep_talk-197", text: "Was macht sie innerlich stark?" },
  { id: "q-deep_talk-198", text: "Was gibt sie anderen mit?" },
  { id: "q-deep_talk-199", text: "Was macht sie bedeutend?" },
  { id: "q-deep_talk-200", text: "Was sollte diese Person öfter über sich selbst glauben – und warum?" },
  { id: "q-deep_talk-201", text: "Welche Wahrheit sollte sie hören – und warum?" },
  { id: "q-deep_talk-202", text: "Was macht sie wirklich glücklich – und warum?" },
  { id: "q-deep_talk-203", text: "Welche Stärke trägt sie durch schwere Zeiten – und warum?" },
  { id: "q-deep_talk-204", text: "Was macht ihr Leben wertvoll – und warum?" },
  { id: "q-deep_talk-205", text: "Welche Eigenschaft macht die Welt besser – und warum?" },
  { id: "q-deep_talk-206", text: "Was lernt man von ihr – und warum?" },
  { id: "q-deep_talk-207", text: "Was macht sie innerlich stark – und warum?" },
  { id: "q-deep_talk-208", text: "Was gibt sie anderen mit – und warum?" },
  { id: "q-deep_talk-209", text: "Was macht sie bedeutend – und warum?" },
  { id: "q-creative-210", text: "Welche Superkraft hätte sie?" },
  { id: "q-creative-211", text: "Welches Pokémon wäre sie?" },
  { id: "q-creative-212", text: "Welche Fantasyklasse wäre sie?" },
  { id: "q-creative-213", text: "Welches Buchgenre beschreibt sie?" },
  { id: "q-creative-214", text: "Welches Videospiel wäre sie?" },
  { id: "q-creative-215", text: "Welches magische Artefakt wäre sie?" },
  { id: "q-creative-216", text: "Welcher Planet passt zu ihr?" },
  { id: "q-creative-217", text: "Welche erfundene Auszeichnung würde sie gewinnen?" },
  { id: "q-creative-218", text: "Welcher Schatz wäre nach ihr benannt?" },
  { id: "q-creative-219", text: "Welche Legende würde über sie erzählt werden?" },
  { id: "q-creative-220", text: "Welche Superkraft hätte sie – und warum?" },
  { id: "q-creative-221", text: "Welches Pokémon wäre sie – und warum?" },
  { id: "q-creative-222", text: "Welche Fantasyklasse wäre sie – und warum?" },
  { id: "q-creative-223", text: "Welches Buchgenre beschreibt sie – und warum?" },
  { id: "q-creative-224", text: "Welches Videospiel wäre sie – und warum?" },
  { id: "q-creative-225", text: "Welches magische Artefakt wäre sie – und warum?" },
  { id: "q-creative-226", text: "Welcher Planet passt zu ihr – und warum?" },
  { id: "q-creative-227", text: "Welche erfundene Auszeichnung würde sie gewinnen – und warum?" },
  { id: "q-creative-228", text: "Welcher Schatz wäre nach ihr benannt – und warum?" },
  { id: "q-creative-229", text: "Welche Legende würde über sie erzählt werden – und warum?" },
];

/** Pick `count` random questions from the full pool. */
export function getRandomQuestions(count: number): MockQuestion[] {
  const shuffled = [...ALL_QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
